name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: add curl
        run: sudo apt-get install libcurl4-openssl-dev
      - name: configure
        run: ./configure
      - name: cmake with fetching
        run: cmake -DUSE_EXTERNAL_DPP=OFF -DUSE_EXTERNAL_JSON=OFF
      - name: make
        run: make
