name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev -y
      - name: Apply Configure
        run: ./configure
      - name: Cmake With Fetching External Dependencies
        run: cmake -DUSE_EXTERNAL_DPP=OFF -DUSE_EXTERNAL_JSON=OFF
      - name: Make
        run: make
