name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
    branch:
      - main

env:
  REGISTRY: ghcr.io

release:
  name: Release
  runs-on: ubuntu-latest
  # Add "id-token" with the intended permissions.
  permissions:
    contents: read
    id-token: write
    packages: write
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker - Auth to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}
        tags: |
          # branch event
          type=ref,event=branch
          # tag event
          type=ref,event=tag
          # sha
          type=sha
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
